language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t aslam0746/docker-react -f Dockerfile.dev .


script:
  - docker run aslam0746/docker-react npm run test -- -- coverage